#!/usr/bin/env sh

# Only auto-format desktop TS code if relevant files are modified
if git diff --cached --name-only | grep -q "^ui/desktop/"; then
  . "$(dirname -- "$0")/_/husky.sh"
  cd ui/desktop && npx lint-staged
fi